services:
  kokoro-tts:
    container_name: kokoro-tts
    # tty: true
    restart: unless-stopped
    ports:
      - 8880:8880
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
